spring:
  application:
    name: COLLEGE-SERVICE

server:
  port: 8787
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultzoe: http://localhost:8761/eureka/
  instance:
    hostname: localhost
       
   